export { default as Behance } from "./behance.svg";
export { default as ButtonTriangle } from "./button-triangle.svg";
export { default as Figma } from "./figma.svg";
export { default as Instagram } from "./instagram.svg";
export { default as LinkedIn } from "./linked-in.svg";
export { default as Logo } from "./logo.svg";
export { default as Sparkles } from "./sparkles.svg";
export { default as NextButton } from "./next-button.svg";
export { default as DownButton } from "./down-button.svg";
